services:
  db:
    image: postgres:15
    container_name: taskdb
    restart: always
    env_file:
      - ./api/.env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file:
      - ./api/.env.prod
    command: redis-server --requirepass redispassword
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  api:
    build: ./api
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env.prod
    depends_on:
      - db
      - redis
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge